--- #YAML:1.0
name: Class-DBI-FormBuilder
version: 0.481
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: Class::DBI/CGI::FormBuilder integration
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
