--- #YAML:1.0
name: Class-DBI-FormBuilder
version: 0.121
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: Class::DBI/CGI::FormBuilder integration
license: perl
requires:
  CGI::FormBuilder: 0
  Class::DBI: 0
  Class::Data::Inheritable: 0
  Test::Exception: 0
  Test::More: 0
provides:
  Class::DBI::FormBuilder:
    file: lib/Class/DBI/FormBuilder.pm
    version: 0.121
generated_by: Module::Build version 0.2609
