---
name: Class-DBI-FormBuilder
version: 0.47
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: Class::DBI/CGI::FormBuilder integration
license: perl
requires:
  CGI::FormBuilder: 3
  Class::DBI: 0
  Class::Data::Inheritable: 0
  List::Util: 0
  Test::Exception: 0
  Test::More: 0
  UNIVERSAL::require: 0
provides:
  Class::DBI::FormBuilder:
    file: lib/Class/DBI/FormBuilder.pm
    version: 0.47
  Class::DBI::FormBuilder::Meta::Column:
    file: lib/Class/DBI/FormBuilder/Meta/Column.pm
  Class::DBI::FormBuilder::Meta::Table:
    file: lib/Class/DBI/FormBuilder/Meta/Table.pm
generated_by: Module::Build version 0.2609
